#!/usr/bin/perl
# countlines.pl by Bill Weinman <http://bw.org/contact/>

use 5.18.0;
use warnings;
$| = 1; #flushing the buffer
# use a scalar variable for the name of the file

my %students = (
    student1 => [45,60,90,90,70],
    student2 => [70,70,70,70,70],
    student3 => [60,95,90,90,70],
    student4 => [50,60,100,90,70],
);

my %average;
my %firstCourse;

for my $key (keys %students){
    my $sum;
    for my $i (0.. $#{$students{$key}}){
        $sum += $students{$key}[$i];
    }
    $average{$key} = $sum / ($#{$students{$key}} +1);
    $firstCourse{$key} = $students{$key}[0];
}
for my $key (keys %average){
    print "$key: ";
    say "GPA = $average{$key}";
}
my ($min, $max, $minCourse1, $maxCourse1);
my ($minKey, $maxKey, $minCourse1Key, $mixCourse1Key);
for my $key (keys %average){
     if (!$min || $average{$key} < $min){
        $min = $average{$key};
        $minKey = $key;
    }
     if (!$max || $average{$key} > $max){
        $max = $average{$key};
        $maxKey = $key;
    }
}
for my $key (keys %firstCourse){
     if (!$minCourse1 || $firstCourse{$key} < $minCourse1){
        $minCourse1 = $firstCourse{$key};
        $minCourse1Key = $key;
    }
     if (!$maxCourse1 || $firstCourse{$key} > $maxCourse1){
        $maxCourse1 = $firstCourse{$key};
        $mixCourse1Key = $key;
    }
}
say "min gpa : ".$minKey . " " . $min;
say "max gpa : ".$maxKey . " " . $max;

say "min grade course 1 : ".$minCourse1 . " " . $minCourse1Key;
say "max grade course 1 : ".$maxCourse1 . " " . $mixCourse1Key;
